export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const AUTH_DETAILS_REQUEST = 'AUTH_DETAILS_REQUEST';
export const AUTH_DETAILS_SUCCESS = 'AUTH_DETAILS_SUCCESS';
export const AUTH_DETAILS_FAIL = 'AUTH_DETAILS_FAIL';
export const AUTH_DETAILS_RESET = 'AUTH_DETAILS_RESET';

export const AUTH_UPDATE_PASSWORD_REQUEST = 'AUTH_UPDATE_PASSWORD_REQUEST';
export const AUTH_UPDATE_PASSWORD_SUCCESS = 'AUTH_UPDATE_PASSWORD_SUCCESS';
export const AUTH_UPDATE_PASSWORD_FAIL = 'AUTH_UPDATE_PASSWORD_FAIL';
export const AUTH_UPDATE_PASSWORD_RESET = 'AUTH_UPDATE_PASSWORD_RESET';
